sudo: required
services:
    - docker
before_install:
    - docker build -t komireddychandureddy/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run komireddychandureddy/react-test npm test -- --coverage

after_success:
    - docker build -t komireddychandureddy/multi-client ./client
    - docker build -t komireddychandureddy/multi-nginx ./nginx
    - docker build -t komireddychandureddy/multi-worker ./worker
    - docker build -t komireddychandureddy/multi-server ./server
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push komireddychandureddy/multi-client
    - docker push komireddychandureddy/multi-nginx
    - docker push komireddychandureddy/multi-worker
    - docker push komireddychandureddy/multi-server
deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-360617681981
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY